### ISSUE TITLE
property 'File' cannot be found on this object

### ISSUE THREAD

**Issue by zacharyshupp** [nightroman/Invoke-Build#215]
I'm having the below issue getting invoke-build to run on PowerShell 7.4.0. When I try to call Invoke-Build straight from the command line I have the same issue where it doesn't like what was passed to -File. 

```Powershell
PS D:\Development\ps-module-base> .\build.ps1 -Task "SetEnv" -Verbose
VERBOSE: Loading module from path 'D:\Development\ps-module-base\dependencies\InvokeBuild\5.10.4\InvokeBuild.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module InvokeBuild.
VERBOSE: Loading module from path 'D:\Development\ps-module-base\dependencies\InvokeBuild\5.10.4\InvokeBuild.psm1'.
VERBOSE: Importing alias 'Build-Checkpoint'.
VERBOSE: Importing alias 'Build-Parallel'.
VERBOSE: Importing alias 'Invoke-Build'.
VERBOSE: Build Task: D:\Development\ps-module-base\tools\build.tasks.ps1
Invoke-Build.ps1: D:\Development\ps-module-base\build.ps1:130
Line |
 130 |      Invoke-Build -Task $Task -File $projectPath['BuildTasks'] -Result …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'File' cannot be found on this object. Verify that the property exists and can be set.
```

I have replaced $projectPath["BuildTasks"] with the actual path and I still get the same error. If I run this in PowerShell 5.1 it runs without issues. 

Operating System: Windows 10 21h2
PowerShell Version:
```
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Below is my build.ps1 script I use. 

```PowerShell
<#
    .SYNOPSIS
        Build wrapper for <some> module/script

    .EXAMPLE
        <Example goes here. Repeat this attribute for more than one example>
#>

[CmdletBinding()]
param (

    # Specifies if the Dependencies should be installed.
    [Parameter()]
    [switch]
    $InstallDependencies,

    # Specifies the powershell gallery to use.
    [Parameter()]
    [string]
    $GalleryName = "PSGallery",

    # Specifies the powershell repository url/unc path.
    [Parameter()]
    [string]
    $GalleryPath = "https://www.powershellgallery.com/api/v2",

    # Specifies the Task(s) to run.
    [Parameter()]
    [string[]]
    $Task

)

# [ProjectDetails] -----------------------------------------------------------------------------------------------------

$projectParams = @{
    ModuleName  = "MyToolbox"
    Guid        = "bdcdffdb-351c-4e5b-a6e7-931a6c400a05"
    Author      = "Zachary Shupp"
    Description = "PowerShell module to ..."
    CompanyName = "SuperAwesomeModules"
    ProjectUri  = "https://github.com/zacharyshupp/MyToolbox"
    LicenseUri  = "https://github.com/zacharyshupp/MyToolbox/blob/main/LICENSE"
    Tags        = @('MyToolbox', 'Toolbox')
}

$requiredModules = @{
    InvokeBuild = 'Latest'
}

# [Initializations] ----------------------------------------------------------------------------------------------------



# [Declarations] -------------------------------------------------------------------------------------------------------

$env:ModuleName = $projectParams.ModuleName
$env:ProjectRoot = $PSScriptRoot

# Core Project specific variables/paths for easy task access.
$projectPath = [Ordered]@{
    Source = Join-Path -Path $PSScriptRoot -ChildPath "source"
    Tools  = Join-Path -Path $PSScriptRoot -ChildPath "tools"
    Output = Join-Path -Path $PSScriptRoot -ChildPath "output"
    Tests  = Join-Path -Path $PSScriptRoot -ChildPath "tests"
    Docs   = Join-Path -Path $PSScriptRoot -ChildPath "docs"
    Deps   = Join-Path -Path $PSScriptRoot -ChildPath "dependencies"
}

# Additional Tools Variables
$projectPath.Add("BuildTasks", $(Join-Path -Path $projectPath['Tools'] -ChildPath 'build.tasks.ps1'))
$projectPath.Add("BuildFunctions", $(Join-Path -Path $projectPath['Tools'] -ChildPath 'build.functions.ps1'))

# [Execution] ----------------------------------------------------------------------------------------------------------

if ($InstallDependencies) {

    # Remove Build Modules directory if it already exists.
    if ((Test-Path -Path $projectPath['Deps']) -eq $true) {
        Remove-Item -Path $projectPath['Deps'] -Recurse -Force -Confirm:$false -ErrorAction Stop
    }

    # Find Gallery
    $gallery = Get-PSRepository -Name $GalleryName

    if (!$gallery) {

        $params = @{
            Name               = $GalleryName
            SourceLocation     = $GalleryPath
            InstallationPolicy = "Trusted"
            ErrorAction        = Stop
        }

        Register-PSRepository @params

    }

    if ($gallery -and $gallery.InstallationPolicy -eq "Untrusted") { 
        Set-PSRepository -Name $GalleryName -InstallationPolicy Trusted -ErrorAction Stop
    }
  
    # Save Modules
    $requiredModules.GetEnumerator() | ForEach-Object {

        Write-Verbose "Found '$($_.Key)' with a value of '$($_.Value)'"

        $galleryParams = @{
            Name               = $_.Key
            Force              = $true
            Path               = $projectPath['Deps']
            ErrorAction        = 'Stop'
        }

        if ($_.Value -ne 'Latest') { $gallaryParams.Add('RequiredVersion', $_.Value) }

        Save-Module @galleryParams

    }

}

if($Task){

    $ibModulePath = Join-Path -Path $projectPath['Deps'] -ChildPath "InvokeBuild"
    Import-Module $ibModulePath -Global -Force -ErrorAction Stop

    Write-Verbose "Build Task: $($projectPath['BuildTasks'])"

    Invoke-Build -Task $Task -File $projectPath['BuildTasks'] -Result 'Result'

}
```

**Comment by nightroman** [comment]
When it happens, could you please examine `$Error` for more details? Any extra hints?

**Comment by nightroman** [comment]
I think the actual problem might be elsewhere and `$Error` may reveal it.

**Comment by zacharyshupp** [comment]
Below is what I can pull from $error. Let me know if there is a specific field you would like to see? I did load this module to a git repo if you want to play with it. 

https://github.com/zacharyshupp/ps-module-base

```PowerShell
PS D:\Development\ps-module-base> $error
Invoke-Build.ps1: D:\Development\ps-module-base\build.ps1:146:5
Line |
 146 |      Invoke-Build -Task $Task -File $projectPath['BuildTasks'] -Result …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'File' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: D:\Development\ps-module-base\dependencies\InvokeBuild\5.10.4\Invoke-Build.ps1:109:1    
Line |
 109 |  ${*}.File = $BuildFile
     |  ~~~~~~~~~~~~~~~~~~~~~~
     | The property 'File' cannot be found on this object. Verify that the property exists and can be set.

PS D:\Development\ps-module-base> $error | Select *

PSMessageDetails      : 
Exception             : System.Exception: The property 'File' cannot be found on this object. Verify that the property exists and can 
                        be set.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : 
CategoryInfo          : InvalidArgument: (:) [Invoke-Build.ps1], Exception
FullyQualifiedErrorId : Invoke-Build.ps1
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at *Die, D:\Development\ps-module-base\dependencies\InvokeBuild\5.10.4\Invoke-Build.ps1: line 31
                        at <ScriptBlock><DynamicParam><trap>, 
                        D:\Development\ps-module-base\dependencies\InvokeBuild\5.10.4\Invoke-Build.ps1: line 43
                        at <ScriptBlock><DynamicParam>, 
                        D:\Development\ps-module-base\dependencies\InvokeBuild\5.10.4\Invoke-Build.ps1: line 109
                        at <ScriptBlock>, D:\Development\ps-module-base\build.ps1: line 146
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: The property 'File' cannot be found on this object. Verify     
                        that the property exists and can be set.
                           at CallSite.Target(Closure, CallSite, Object, Object)
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)     
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : PropertyNotFound
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock><DynamicParam>,
                        D:\Development\ps-module-base\dependencies\InvokeBuild\5.10.4\Invoke-Build.ps1: line 109
                        at <ScriptBlock>, D:\Development\ps-module-base\build.ps1: line 146
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

**Comment by nightroman** [comment]
Thank you. That gives more insights.
Unfortunately your cloned project works just in 7.4.0 just fine for me :(

How did you install 7.4.0? I use the zip variant downloaded from the release page -- https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0
Can you try? Because I have not ideas what wrong is, apart from your different install or environment.

**Comment by nightroman** [comment]
Can you please also try calling IB without the result, i.e. remove `-Result 'Result'` from
```
    Invoke-Build -Task $Task -File $projectPath['BuildTasks'] -Result 'Result'
```
(the script does not use the result anyway, this demo script at least)

**Comment by nightroman** [comment]
Then, we have to understand what's going on in your case at line
```
109 |  ${*}.File = $BuildFile
```
Can you please go to `Invoke-Build.ps1` to that line and log (use `Write-Host`, `Out-String`, `${*}.GetType()`, etc., anything that may help). Obviously `${*}` is not quite right.

**Comment by zacharyshupp** [comment]
For PowerShell I have it installed via the x64 MSI they provide.  I did try running it without the results and I have the same issue. 

I did add a couple of checks to invoke-build.ps1 and its like ${*} doesn't exists. 

Below is the output, you can see that the script got the path I provided. I added `Write-Host "File Passed: '$($PSBoundParameters['File'])'"`  right before the `New-Variable * -Description IB ([PSCustomObject]@{` line in Invoke-Build.ps1. I added `Write-Host "Started: $(${*}.Started)"` to right above 109 and you can see from below it comes back with no value for started which makes me think ${*} never gets created.

```PowerShell
PS D:\Development\ps-module-base> .\build.ps1 -Task Build
File Passed: 'D:\Development\ps-module-base\tools\build.tasks.ps1'
Started: 
Invoke-Build.ps1: D:\Development\ps-module-base\build.ps1:146:5
Line |
 146 |      Invoke-Build -Task $Task -File "D:\Development\ps-module-base\too …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'File' cannot be found on this object. Verify that the property exists and can be set.
```

When I run `${*}.GetType()` I get nothing back.

**Comment by nightroman** [comment]
I've run out of ideas for the moment.
- Maybe the new PS does snot like the name? Try to hack / use a different variable instead of `*`. Try to run with the completely clean session with no profile. 
- Do you have some function custom or alias `New-Variable` by any chance? Try `gcm New-Variable -all` before running.

**Comment by nightroman** [comment]
- Pester may do something about `New-Variable`, too, try without Pester, I see
```
    'New-Variable'         = & $Get_Command -Name New-Variable         -Module Microsoft.PowerShell.Utility    @safeCommandLookupParameters
```

**Comment by nightroman** [comment]
- try `gcm New-Variable` in Invoke-Build.ps1 before it is called. Is it what we expect, the usual PS cmdlet?

**Comment by zacharyshupp** [comment]
I dont have any aliases setup. I did try without pester and was having the same issue. 

I did uninstall 7.4 and reinstalled 7.3.10 and with that installed I have no issue with running my code. I tried running the 7.4 as an update and once it was applied this stopped working again.

**Comment by zacharyshupp** [comment]
ugh, I just did the same test you did with running the zip of 7.4.0 and running that it works as well, so something is getting messed up using the MSI installer and Im at a loss.

**Comment by nightroman** [comment]
> ugh, I just did the same test you did with running the zip of 7.4.0 and running that it works as well, so something is getting messed up using the MSI installer and Im at a loss.

Maybe report this to https://github.com/PowerShell/PowerShell?

**Comment by nightroman** [comment]
Hi @zacharyshupp They added a commend/guess there. Could you please try to remove `[PSCustomObject]` from
```
New-Variable * -Description IB ([PSCustomObject]@{
```

Just to understand that this really is the reason.

**Comment by nightroman** [comment]
Or try this suggestion

> Could you try and temporarily disable Constrained Language Audit Mode, and see if that makes a difference?

Because removing `[PSCustomObject]` is just one place will probably just move us to another errors.

**Comment by zacharyshupp** [comment]
I did try what they had for a workaround, and it did not work for me. I tried `$ExecutionContext.SessionState.LanguageMode = 'FullLanguage'` but that also didn't seem to change anything. I was reading and it seems like folks have mixed results disabling it.

**Comment by nightroman** [comment]
All right... In any case, the problem seems to be elsewhere outside IB, so I am closing the issue. But I'll keep an eye on this development. Feel free to reopen or create a new issue when an action is needed in IB.
